accent = "#9bb0c2"
cursor = "#d4d5d9"
foreground = "#d4d5d9"
background = "#0a0f1c"
selection_foreground = "#0a0f1c"
selection_background = "#d4d5d9"

color0 = "#0a0f1c"
color1 = "#869aac"
color2 = "#95a8b8"
color3 = "#9fadb8"
color4 = "#9bb0c2"
color5 = "#a8b9c6"
color6 = "#b8c7d0"
color7 = "#d4d5d9"
color8 = "#5f6374"
color9 = "#869aac"
color10 = "#95a8b8"
color11 = "#9fadb8"
color12 = "#9bb0c2"
color13 = "#a8b9c6"
color14 = "#b8c7d0"
color15 = "#d4d5d9"
